import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/contexts/Providers';
import { Footer, Navbar } from '@/components';
import { NFTProvider } from '@/contexts/NFTContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NFTProvider>
            <div className="dark:bg-nft-dark bg-white min-h-screen">
              <Navbar />
              <main className="pt-65">{children}</main>
              <Footer />
            </div>
          </NFTProvider>
        </Providers>
      </body>
    </html>
  );
}
